### ISSUE TITLE
【要望】更新を通知する機能を追加する(Slack)

### ISSUE THREAD

**Issue by hirotoKirimaru** [budougumi0617/blog-kpi-collector#13]
# 概要
KPIを取得した結果をメールやSlack等で知り、情報の取得をpullではなくpush型にする。  

# バージョン情報
`clasp --version`の実行結果を書いてください。
なし

# 再現手順
なし

# 修正しないとどう困るか
情報を一々取得しに行く必要がある。

# 原因
なし

# 修正案
下記ページのソースコードで通知できる機能を追加できそう。  
  
https://toranoana-lab.hatenablog.com/entry/2020/03/13/173949

**Comment by budougumi0617** [comment]
新しくトリガーを設定するのも良さそうですが、今あるスクリプトに書き込みしたあと最後に通知するように実装してもいいかもせれませんね。
今あるスクリプトで書き込む以外のことはあまりないかなーと思うので

**Comment by hirotoKirimaru** [comment]
はい。
今あるスクリプトの最後の処理でSlack通知をつけようと考えてます。

スクリプトのプロパティに設定されていなければ処理をスルーする感じで。

**Comment by hirotoKirimaru** [comment]
#14 
マージリクエストを作りました。
